### ISSUE TITLE
Jazzy cannot find dictionary

### ISSUE THREAD

**Issue by eyalhoc** [reckart/jazzy#1]
The example code writes:
private final String DICTIONARY_FILE = "resources/english.0";

I downloaded the dictionary but where am I supposed to put the resources directory so SpellDictionaryHashMap() will find it?

**Comment by reckart** [comment]
I cloned this software ages ago, but I'm not maintaining it. Basically, it's just an old repo hanging around on my GitHub account. Sorry, but I don't have answer for your question.

**Comment by eyalhoc** [comment]
Thanks for answering. Perhaps you can help anway.
I'm trying to use a spell checker for an android app. Google's spell
checker service runs but always returns empty suggestions.
So, I'm looking for an alternative..
I found quite a few but none run on android.

Perhaps you can suggest something.

Thanks,
Eyal

**Comment by reckart** [comment]
I'm afraid, I don't have any suggestions for alternatives. Probably best try figuring out why the ob-board spell checker doesn't work for you and try fixing that problem.

**Comment by eyalhoc** [comment]
Thanks
